# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Setup Poetry
      # You may pin to the exact commit or the version.
      # uses: Gr1N/setup-poetry@09236184f6c1ab47c0dc9c1001c7fe200cf2afb0
      uses: Gr1N/setup-poetry@v7
      with:
        # Allow to install prerelease versions of Poetry
        poetry-preview: # optional, default is false
        # Poetry version to use, if version is not provided then latest stable version will be used
        poetry-version: # optional
    - name: Show Debugging Information
      run: |
        env
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        poetry install --no-root
    - name: Lint with pylint
      run: |
        export PYTHONPATH=.:${PYTHONPATH}
        # stop the build if there are Python syntax errors or undefined names
        poetry run pylint il_elections --rcfile=.pylintrc
    - name: Test with pytest
      run: |
        export PYTHONPATH=.:${PYTHONPATH}
        poetry run pytest
